name: mason_bug
description: A mason bug on windows
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  mason:
    git:
      url: https://github.com/felangel/mason
      path: packages/mason
